acl:
    roles: []
    resources:
        allow: []
        deny: []
    default_role: guest
    
    # permissive - allow access to unconfigured resource
    # restrictive - deny access to unconfigured resource
    policy: restrictive
    violation_handlers:
        unauthenticated: ~
        unauthorized: ~
    role_resolver: ZfExtra\Acl\RoleProvider\RoleResolver
            
service_manager:
    factories:
        acl: ZfExtra\Acl\Service\AclServiceFactory
        ZfExtra\Acl\AclListener: ZfExtra\Acl\Factory\AclListenerFactory
        ZfExtra\Acl\RoleProvider\RoleResolver: ZfExtra\Acl\Factory\RoleResolverFactory
        
zf_annotation:
    annotations:
        - ZfExtra\Acl\Annotation\Acl
    event_listeners:
        - ZfExtra\Acl\Annotation\AnnotationListener