assets:
    module_assets_dir: assets
    install_dir: public/assets

command_manager:
    invokables:
        cli.command.install_assets: ZfExtra\Asset\Command\InstallAssetsCommand

service_manager:
    factories:
        assets: ZfExtra\Asset\Service\AssetManagerFactory
        
view_helpers:
    invokables:
        image: ZfExtra\Asset\View\Helper\Image