controller_plugins:
    invokables:
        config:  ZfExtra\Config\Controller\Plugin\Config

view_helpers:
    invokables:
        config: ZfExtra\Config\View\Helper\Config

service_manager:
    aliases:
        config.helper: ZfExtra\Config\ConfigHelper
        config_helper: ZfExtra\Config\ConfigHelper
    factories:
        ZfExtra\Config\ConfigHelper: ZfExtra\Config\ConfigHelperFactory