controller_plugins:
    invokables:
        config:  ZfExtra\Config\Controller\Plugin\Config

view_helpers:
    invokables:
        config: ZfExtra\Config\View\Helper\Config

service_manager:
    aliases:
        config_helper: config.helper
    factories:
        config.helper: ZfExtra\Config\ConfigHelperFactory