logger:
    enable: true
    service: ZfExtra\Log\ApplicationLogger
    formatter: ZfExtra\Log\ApplicationLoggerFormatter
    priority: 6
    writers:
        - ZfExtra\Log\ApplicationLoggerStreamWriter
    filters:
        - ZfExtra\Log\ApplicationLoggerPriorityFilter
    
service_manager:
    factories:
        ZfExtra\Log\EventListener\LogEventListener: ZfExtra\Log\Factory\LogEventListenerFactory
        ZfExtra\Log\ApplicationLogger: ZfExtra\Log\Factory\ApplicationLoggerFactory
        ZfExtra\Log\ApplicationLoggerFormatter: ZfExtra\Log\Factory\ApplicationLoggerFormatterFactory
        ZfExtra\Log\ApplicationLoggerStreamWriter: ZfExtra\Log\Factory\ApplicationLoggerStreamWriterFactory
        ZfExtra\Log\ApplicationLoggerPriorityFilter: ZfExtra\Log\Factory\ApplicationLoggerPriorityFilterFactory
        
