'@includes': 
    - variables.yml
    - doctrine.yml
    - mailer.yml
    - twig.yml
    - console.yml
    - assets.yml
    - assertion.yml
    - view.yml
    - config.yml
    - user.yml
    - intl.yml
    - mvc.yml
    - acl.yml
    - events.yml
    - log.yml

service_manager:
    factories:
        mailer: ZfExtra\Mail\MailerFactory
        events: ZfExtra\EventManager\EventManagerFactory
        Application: ZfExtra\Mvc\ApplicationFactory
        fs.local: ZfExtra\Filesystem\LocalFilesystemFactory
    invokables:
        listener.event_subscriber: ZfExtra\EventListener\MasterEventSubscriber
        listener.assertions: ZfExtra\Assertion\Listener\AssertionListener
    initializers:
        - ZfExtra\EventManager\EventsInitializer
    
listeners:
    - listener.event_subscriber
    - listener.assertions
    