mvc:
    doctrine_object_injector:
        object_managers:
            orm: doctrine.entitymanager.orm_default
        object_mapping:
            orm:
                - ZfExtra\Entity\EntityInterface
        injections: []
            
assertions:
    invokables:
        required: ZfExtra\Mvc\Assertion\Required
            
controller_plugins:
    invokables:
        service: ZfExtra\Controller\Plugin\Service
        session: ZfExtra\Controller\Plugin\Session
        view:    ZfExtra\Controller\Plugin\View
        mailer:  ZfExtra\Controller\Plugin\Mailer
        events:  ZfExtra\Controller\Plugin\Events
        translate:  ZfExtra\Controller\Plugin\Translate
        form:  ZfExtra\Controller\Plugin\Form
    factories:
        render:  ZfExtra\Controller\Factory\RenderPluginFactory
    initializers:
        - ZfExtra\EventManager\EventsInitializer
            
service_manager:
    aliases:
        ZfExtra\Mvc\Listener\DoctrineObjectInjectionListener: doctrine_object_injector_listener
    invokables:
        doctrine_object_injector_listener: ZfExtra\Mvc\Listener\DoctrineObjectInjectionListener
        ZfExtra\Mvc\Listener\RequestLifecycleLogListener: ZfExtra\Mvc\Listener\RequestLifecycleLogListener
    factories:
        doctrine_object_injector: ZfExtra\Mvc\Factory\DoctrineObjectInjectorFactory