service_manager:
    factories:
        twig.environment: ZfExtra\Twig\Service\TwigFactory
        twig.renderer: ZfExtra\Twig\Service\RendererFactory
        twig.resolver: ZfExtra\Twig\Service\TwigResolverFactory
        twig.loader: ZfExtra\Twig\Service\LoaderFactory
        twig.loader.path_stack: ZfExtra\Twig\Service\PathStackLoaderFactory
        listener.twig.strategy: ZfExtra\Twig\Service\TwigStrategyFactory

twig:
    options:
        debug: false
        charset: UTF-8
        base_template_class: Twig_Template
        cache: false
        auto_reload: ~
        strict_variables: false
        autoescape: html
        optimizations: -1
    loaders:
        - twig.loader.path_stack
    extensions: []
        