auth:
    service: ~
    options:
        request_key_identity: email
        request_key_credential: password
    redirect:
        after_login: ~
        after_logout: ~
    
user:
    entity_class: ~
    
service_manager:
    factories:
        auth: ZfExtra\User\Service\AuthFactory
        user_manager: ZfExtra\User\Service\UserManagerFactory
        
command_manager:
    invokables:
        cli.command.user.create: ZfExtra\User\Command\CreateUserCommand