variables:
    mailer:
        transport: Zend\Mail\Transport\File
        transport_options: 
            path: data/mail
#            callback: [App\Module, method]

    doctrine:
        host: localhost
        port: 3306
        user: root
        password: ~
        dbname: ~
        driver_options: 
            1002: SET NAMES utf8
        charset: utf8