view_layouts:
    order: [action, controller, module, route]
    layouts:
        route: []
        module: []
        controller: []
        action: []

view_helpers:
    aliases: []
    
service_manager:
    factories:
        ZfExtra\View\DirectRenderer: ZfExtra\View\Factory\DirectRendererFactory
    